import './js/header';
import './js/switcher-theme';
import './js/modal_cocktail';
import './js/modalIng';
import './js/hero';
import './js/customselect';
import './js/random';
import './js/addCoctToFav';
import './js/scroll-up.js/scroll-up';
